### ISSUE TITLE
Pin out

### ISSUE THREAD

**Issue by brando9182** [rsegecin/ArduinoBMX055#1]
Hey Rsegecin. Just wondering if you had a mapping of the connections you made form the IMU to the arduino.

**Comment by rsegecin** [comment]
Hi Brando. I just made a voltage divider for each BMX's input pin having the arduino's output pins as a source it still on my protoboard I didn't have time to make an schematic.

**Comment by brando9182** [comment]
Thank you. One more question. 
Where did you get the 0x80 offset came from (when you SPI.transfer)?

**Comment by rsegecin** [comment]
I uploaded the BMX's datasheet. On page 143 you can see that to perform a read operation you need to set the first bit high concatenated with the register you want to read. I uploaded the last version that I was working on with some comments. The gyroscope still need work to be done because as far my research went you've to do some math to get it's value right and from what I remember you've to get the difference between the current and the last gyro's value and divide for how long you took to make those measurements (something like that). I'd be glad if you could figure how to read the gyroscope and submitted here because I don't know whether I'm going to have time to finish this project.

**Comment by rsegecin** [comment]
Brando have you got the bmx module sorted out? Did you make the gyroscope to work? if you did please request a pull up and share your findings.
